# Generated by Django 2.2.28 on 2023-12-12 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_auto_20230919_1113"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualRestaurant",
            fields=[
                (
                    "restaurant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="restaurant.Restaurant",
                    ),
                ),
                (
                    "secret",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=16, max_length=16, prefix=""
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("restaurant.restaurant",),
        ),
        migrations.CreateModel(
            name="Special",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(default=datetime.date.today)),
                ("end", models.DateField()),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=outpost.django.base.utils.Uuid4Upload,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.Restaurant",
                    ),
                ),
            ],
        ),
    ]
