# Generated by Django 2.2.28 on 2024-04-26 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_manualrestaurant_special"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="meal",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="special",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="meal",
            name="foreign",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="special",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specials",
                to="restaurant.Restaurant",
            ),
        ),
    ]
