# Generated by Django 2.2.28 on 2024-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_auto_20240426_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special",
            name="start",
            field=models.DateField(),
        ),
    ]
