# Generated by Django 2.2.28 on 2025-02-12 08:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_auto_20240507_1330"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginRestaurant",
            fields=[
                (
                    "restaurant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="restaurant.Restaurant",
                    ),
                ),
                ("configuration", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "behaviour",
                    models.CharField(
                        choices=[
                            (
                                "outpost.django.restaurant.plugins.DebugRestaurantBehaviour",
                                "Debugger",
                            ),
                            (
                                "outpost.django.restaurant.plugins.MensenRestaurantBehaviour",
                                "Mensen",
                            ),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "default_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.Diet",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("restaurant.restaurant",),
        ),
        migrations.CreateModel(
            name="DietMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("value", models.CharField(max_length=512)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.Diet",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.PluginRestaurant",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
