# Generated by Django 5.2.16 on 2026-09-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("restaurant", "0010_dietmap_pluginrestaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseextractor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="manualrestaurant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pluginrestaurant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="xmlrestaurant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="xsltextractor",
            options={},
        ),
        migrations.AlterField(
            model_name="baseextractor",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="pluginrestaurant",
            name="configuration",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="consumers",
            field=models.ManyToManyField(related_name="+", to="api.consumer"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
